services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

    volumes:
      - ./data/mongo:/data/db
  api:
    restart: always
    build: 
      context: ./api
      dockerfile: Dockerfile.debug
    volumes:
      - ./api:/usr/src/app

    ports:
      - 8000:8000

    environment:
      - MONGO_URI=mongodb://mongo:27017
      - ROOT_USER=root
      - ROOT_PASSWORD=root
      - RECREATE_ROOT=false
      - ALLOW_ACCOUNT_CREATION=true
      - STORE_LOCATION=Rochester Institute of Technology
      - STORE_SUPPORT=wegmans,costco
      - SESSION_EXPIRE=259200

    stop_signal: SIGINT
    depends_on:
      - mongo

  client:
    restart: always
    build: 
      context: ./lia
      dockerfile: Dockerfile.debug
    volumes:
      - ./lia:/usr/src/app

    ports:
      - 5173:5173

    depends_on:
      - api